version: '3.5'

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "mssql"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=2wsx2WSX
    restart: always
    networks: 
      - bookshop-network
networks:
  bookshop-network:
    name: bookshop-network
  
    